### PR TITLE
support Rails 7.1

### PR DESCRIPTION
**Pull request by tomasc**
This PR adds tests against Rails 7.1.

### CODE REVIEW

**Comment by tomasc** [comment]
@crashtech Carlos, could you please help me to get the tests running? I could then try to get this PR pass (unless you of course prefer to do it).

**Comment by tomasc** [comment]
@crashtech I tried to make a few adjustments, but it's quickly getting beyond my knowledge of AR. Perhaps you have suggestions what to update to make things work with Rails 7.1?

The other thing is that for some strange reason, both -7.0 and -7.1 Gemfiles install Rails 7.1. :(

**Comment by tomasc** [comment]
@crashtech Carlos, ok, I think I got us somewhere. Most tests pass on 7.1, except the ones related to inheritance. Perhaps you can take a look?

**Comment by crashtech** [comment]
Please refer to #86. I needed to go on different paths for several of the changes.

**Pull request closed without merging**
