### PR TITLE
Rails 5.2.1

### PR DESCRIPTION
**Pull request by mlt**
This is far from complete as the code is way above my head, but it passes most of the tests for me. Wanna see what Travis has to say.

### CODE REVIEW

**Comment by crashtech** [comment]
Can you rebase, please? Let's try to get this merged.

**Comment by mlt** [comment]
FYI There are still some enum tests failing.

**Comment by crashtech** [comment]
I just finished fixing the specs for 5.2.1
I also reactivated Travis for Pull Requests
We are good to go. If you do have a project using the GEM and Rails 5.2.1, can you give it a try?

**Comment by mlt** [comment]
Tests pass for me on MS Windows with Ruby 2.4.5 alright.
I use very small subset of your gem thus far. Namely, interval support to get ActiveSupport::Duration. That seems to work.

It would be nice to have a small stub for geom columns to suppress OID warning `unless Gem.loaded_specs.has_key? 'activerecord-postgis-adapter'`. I just feel like rgeo/activerecord-postgis-adapter is too heavy for what I need, i.e. spit out GeoJSON from PG directly. I'm not sure whether I shall submit a feature request for that with your gem.

**Comment by mlt** [comment]
While we are at it&hellip; Is it doable/worth doing to relax psql options for now? Since your gem, besides everything else, resolves issues that are not upstream in Rails yet, I think it would make sense to stub this annoying issue https://github.com/rails/rails/<I don't want to pollute their repo with back link and I have no clue how to prevent it so remove this>issues/29049

**Comment by crashtech** [comment]
Great! I understand your usage. I want to add as much as possible PostgreSQL features with this GEM, so we can start sketching how it would feel like with Postgis columns.

I think the first step would be upgrading pg, and removing my own version of the decoder, but keeping retro-compatibility.

I didn't understand your last suggestion. Were you talking about providing a compatibility with `rake db:structure:dump`?

**Comment by crashtech** [comment]
Can you tell me which things are missing?

**Pull request merged**
